services:
  # 后端服务
  - type: web
    name: medical-prediction-api
    env: node
    plan: starter
    buildCommand: |
      cd server && npm install && npm run build
      python3 -m venv /opt/render/project/.venv
      /opt/render/project/.venv/bin/pip install -r ../requirements.txt
      # 创建Python符号链接以确保兼容性
      ln -sf /opt/render/project/.venv/bin/python /opt/render/project/.venv/bin/python3
    startCommand: cd server && node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: PYTHON_PATH
        value: /opt/render/project/.venv/bin/python
      - key: PYTHON
        value: /opt/render/project/.venv/bin/python
      - key: PATH
        value: /opt/render/project/.venv/bin:$PATH
    
  # 前端服务
  - type: web
    name: medical-prediction-web
    env: static
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: ./client/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://medical-prediction-api.onrender.com

databases:
  - name: medical-prediction-db
    databaseName: medical_prediction
    user: medical_user 